[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
bevy = { version = "0.12.0" }

# Test game
bevy-inspector-egui = "0.21.0"
leafwing-input-manager = "0.11.1"
bevy_rapier2d = { version = "0.23.0", features = ["simd-stable"] }
